steps:
  - name: bash
    secretEnv:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    script: |
      #!/usr/bin/env bash
      printenv > .env
  # running docker-compose
  - name: 'docker/compose:1.29.2'
    args: [ 'up', '-d' ]
availableSecrets:
  secretManager:
    - versionName: >-
        projects/$PROJECT_NUMBER/secrets/POSTGRES_USER/versions/latest
      env: POSTGRES_USER
    - versionName: >-
        projects/$PROJECT_NUMBER/secrets/POSTGRES_PASSWORD/versions/latest
      env: POSTGRES_PASSWORD
    - versionName: >-
        projects/$PROJECT_NUMBER/secrets/POSTGRES_DB/versions/latest
      env: POSTGRES_DB